version: 3

services:
  web:
    build: web
    volumes:
      - '${PWD}/web:/etc/twinepm-server-heroku/web'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
      - '${PWD}/web/site.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - logic
      - db
      - cache
    environment:
      MODE: development

  logic:
    build: src
    volumes:
      - '${PWD}/src:/etc/twinepm-server-heroku/src'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
      - '${PWD}/src/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    links:
      - db
      - cache
    environment:
      MODE: development

  db:
    build: db
    volumes:
      - '${PWD}/db:/etc/twinepm-server-heroku/db'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
    expose: 5432
    environment:
      MODE: development

  cache:
    build: cache
    volumes:
      - '${PWD}/cache:/etc/twinepm-server-heroku/cache'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
    expose: 6379
    environment:
      MODE: development