version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - logic
    environment: &mode
      TWINEPM_MODE: development
    networks:
      - backend_web
    ports:
      - '443:80'

  logic:
    build:
      context: .
      dockerfile: logic/Dockerfile
    depends_on:
      - database
      - cache
    environment: *mode
    env_file:
      - logic/.env
    networks:
      - backend_web
      - backend_persistence

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      <<: *mode
      POSTGRES_DB: twinepm
      POSTGRES_USER: root
    networks:
      - backend_persistence

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    environment: *mode
    networks:
      - backend_persistence

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment: *mode
    networks:
      - backend_persistence

networks:
  backend_web:
    driver: bridge
  backend_persistence:
    driver: bridge
  frontend:
    driver: bridge