version: '3'

services:
  web:
    image: furkle/twinepm_web:latest
    ports:
      - '443:80'
    depends_on:
      - php_fpm
    links:
      - php_fpm
    environment: &mode
      MODE: production

  php_fpm:
    image: furkle/php-fpm:latest
    environment: *mode