version: '3'

services:
  web:
    build: web/
    depends_on:
      - logic
      - db
      - cache
    environment: &mode
      MODE: development

  logic:
    build: src/
    links:
      - db
      - cache
    environment: *mode

  db:
    build: db/
    expose:
      - 5432
    environment: *mode 

  cache:
    build: cache/
    expose:
      - 6379
    environment: *mode