version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '443:80'
    depends_on:
      - logic
    environment: &mode
      TWINEPM_MODE: development

  logic:
    build:
      context: .
      dockerfile: logic/Dockerfile
    depends_on:
      - database
      - cache
    environment: *mode
    env_file:
      - logic/.env

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    networks:
      - backend
    environment:
      <<: *mode
      POSTGRES_DB: twinepm
      POSTGRES_USER: root

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    networks:
      - backend
    environment: *mode

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - client
    environment: *mode

networks:
  client:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge