version: '3'

services:
  web:
    volumes:
      - '${PWD}/web:/etc/twinepm-server-heroku/web'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
      - '${PWD}/web/site.conf:/etc/nginx/conf.d/default.conf'
    build: web/
    depends_on:
      - logic
      - db
      - cache
    environment: &mode
      MODE: development

  logic:
    volumes:
      - '${PWD}/src:/etc/twinepm-server-heroku/src'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
      - '${PWD}/src/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    build: src/
    links:
      - db
      - cache
    environment: *mode

  db:
    build: db/
    volumes:
      - '${PWD}/db:/etc/twinepm-server-heroku/db'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
    expose:
      - 5432
    environment: *mode 

  cache:
    volumes:
      - '${PWD}/cache:/etc/twinepm-server-heroku/cache'
      - '${PWD}/build.xml:/etc/twinepm-server-heroku/build.xml'
    build: cache/
    expose:
      - 6379
    environment: *mode