version: '3'

services:
  web:
    image: twinepm/twinepm_web:latest
    ports:
      - '443:80'
    depends_on:
      - logic
    networks:
      - frontend
    environment: &mode
      TWINEPM_MODE: production

  logic:
    image: twinepm/logic:latest
    networks:
      - frontend
      - backend
    environment: *mode
    env_file:
      - logic/.env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge