version: '3'

services:
  web:
    image: furkle/twinepm_web:latest
    ports:
      - '443:80'
    depends_on:
      - php_fpm
    networks:
      - frontend
    environment: &mode
      MODE: production

  php_fpm:
    image: furkle/php-fpm:latest
    networks:
      - frontend
      - backend
    environment: *mode

networks:
  - frontend
  - backend