version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - logic
    environment: &mode
      TWINEPM_MODE: development
    networks:
      - backend
    ports:
      - '443:80'

  logic:
    build:
      context: .
      dockerfile: logic/Dockerfile
    depends_on:
      - database
      - cache
    environment: *mode
    env_file:
      - logic/.env
    networks:
      - backend

  database:
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      <<: *mode
      POSTGRES_DB: twinepm
      POSTGRES_USER: root
    networks:
      - backend

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    environment: *mode
    networks:
      - backend

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    environment: *mode
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge