version: '3'

services:
  web:
    build:
      context: web/
    depends_on:
      - logic
      - db
      - cache
    environment: &mode
      MODE: development

  logic:
    build:
      context: src/
    links:
      - db
      - cache
    environment: *mode

  db:
    build:
      context: db/
    expose:
      - 5432
    context: .
    environment: *mode

  cache:
    build: 
      context: cache/
    expose:
      - 6379
    context: .
    environment: *mode