version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - logic
    environment: &mode
      MODE: development

  logic:
    build:
      context: .
      dockerfile: logic/Dockerfile
    depends_on:
      - db
      - cache
    environment: *mode

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    networks:
      - backend
    environment:
      <<: *mode
      POSTGRES_USER: root

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    networks:
      - backend
    environment: *mode