version: '3'

services:
  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - php_fpm
    environment: &mode
      MODE: development

  php_fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    depends_on:
      - db
      - cache
    links:
      - db
      - cache
    environment: *mode

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment: *mode

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    environment: *mode