version: '3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    depends_on:
      - logic
      - db
      - cache
    environment: &mode
      MODE: development

  logic:
    build:
      context: .
      dockerfile: src/Dockerfile
    links:
      - db
      - cache
    environment: *mode

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    expose:
      - 5432
    context: .
    environment: *mode

  cache:
    build: 
      context: .
      dockerfile: cache/Dockerfile
    expose:
      - 6379
    context: .
    environment: *mode