#! /usr/bin/env python3

import os
import subprocess

# Get the directory in which the file is executing.
dirname = os.path.dirname(os.path.realpath(__file__))

cmd = ['createdb', 'twinepm']
proc = subprocess.Popen(cmd)
proc.communicate()

# Load the database dump into the database.
with open('{}/../twinepm_db_dump'.format(dirname), 'r') as infile:
    cmd = ['psql', 'twinepm']
    proc = subprocess.Popen(cmd, stdin=infile)
    proc.communicate()