#!/bin/sh
apt-get update

TYPE=$(type composer 2> /dev/null)

apt-get install -y php-mbstring &&

if [ "$TYPE" == '' ]; then
    apt-get install -y \
        git \
        unzip \
        zip &&
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" &&
    php /tmp/composer-setup.php \
        --install-dir=/usr/local/bin \
        --filename=composer &&
    rm /tmp/composer-setup.php
fi &&

su www-data &&
cd /etc/twinepm-server-heroku &&
composer install \
    --no-plugins \
    --no-scripts &&
echo "<?php require_once '/etc/twinepm-server-heroku/index.php'; ?>" > /usr/share/nginx/html/index.php