#!/bin/sh
apt-get update

TYPE1=$(type docker-php-ext-install 2> /dev/null)
TYPE2=$(type composer 2> /dev/null)

if [ "$TYPE1" == '' ]; then
    apt-get install -y php-mbstring
else
    docker-php-ext-install -j$(nproc) mbstring
fi &&

if [ "$TYPE2" == '' ]; then
    apt-get install -y \
        git \
        unzip \
        zip &&
    curl -fsSL 'https://getcomposer.org/installer' > /tmp/composer-setup.php &&
    php /tmp/composer-setup.php \
        --install-dir=/usr/local/bin \
        --filename=composer &&
    rm /tmp/composer-setup.php
fi &&

cd /etc/twinepm-server-heroku &&
composer install \
    --no-plugins \
    --no-scripts &&
echo "<?php require_once '/etc/twinepm-server-heroku/index.php'; ?>" > /usr/share/nginx/html/index.php