#! /usr/bin/env python3

import argparse
import shutil
import subprocess
import os
import shutil

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')
compose_override_path = os.path.join(dirname,
                                     '../docker-compose.override.yml')

parser = argparse.ArgumentParser(description='Install dependencies for ' +
                                 'TwinePM\'s PHP-FPM container.')

args = parser.parse_args()


nproc = subprocess.check_output('nproc')
cmd = ['docker-php-ext-install', '-j{}'.format(nproc), 'mbstring']
try:
    proc = subprocess.Popen(cmd)
    proc.communicate()
except:
    cmd = ['apt-get', 'install', '-y', 'php-mbstring']
    proc = subprocess.Popen(cmd)
    proc.communicate()


cmd = ['composer', '-v']
try:
    proc = subprocess.Popen(cmd, cwd='/etc/twinepm-server-heroku')
    proc.communicate()
except:
    cmd = ['apt-get', 'install', '-y', 'git', 'unzip', 'zip']
    proc = subprocess.Popen(cmd)
    proc.communicate()


url = 'https://getcomposer.org/installer'
file_name = '/tmp/composer-setup.php'
with request.urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)

cmd = ['php', '/tmp/composer-setup.php', '--install-dir=/usr/local/bin',
       '--filename=composer']
proc = subprocess.Popen(cmd)
proc.communicate()

os.remove('/tmp/composer-setup.php')

with open('/usr/share/nginx/html/index.php', 'w') as f:
    os.write(f, '<?php require_once "/etc/twinepm-server-heroku/index.php"; ?>')

app_path = '/etc/twinepm-server-heroku/'
shutil.copyfile('{}src/site.conf'.format(app_path),
                '/etc/nginx/conf.d/default.conf')
shutil.copyfile('{}src/mime.types'.format(app_path), '/etc/nginx/')
print('Completed installing web dependencies.')