#! /usr/bin/env python3

import argparse
import shutil
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')
compose_override_path = os.path.join(dirname,
                                     '../docker-compose.override.yml')

parser = argparse.ArgumentParser(description='Install dependencies for ' +
                                 'TwinePM\'s web server container.')

args = parser.parse_args()

cwd = '/etc/twinepm-server-heroku/'
with open('/usr/share/nginx/html/index.php', 'w') as f:
    f.write('<?php require_once "{}logic/index.php"; ?>'.format(cwd))

shutil.copy2('{}web/site.conf'.format(cwd), '/etc/nginx/conf.d/default.conf')
shutil.copy2('{}web/mime.types'.format(cwd), '/etc/nginx/')

print('Completed installing web dependencies.')