#! /bin/bash

if [ "$1" == "fromcache" ] || [ "$1" == "--from-cache" ] || [ "$1" == "-c" ]; then
    docker-compose build
else
    docker-compose build --no-cache
fi &&

shift &&

if [ "$1" == "up" ] || [ "$1" == "--up" ] || [ "$1" == "-u" ]; then
    docker-compose up
fi