#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Destroy the current TwinePM ' +
                                 'virtual machine.')

parser.add_argument('--force', '-f', action='store_true', default=None,
                    help='don\'t ask for confirmation')

args = parser.parse_args()

cmd = ['vagrant', 'destroy']
if args.force:
    cmd.append('--force')

env = os.environ.copy()
env['VAGRANT_CWD'] = dirname
proc = subprocess.Popen(cmd, env=env)
proc.communicate()

print('Destroyed virtual machine.')