#!/bin/sh

apt-get update
if ! type php 2>/dev/null; then
  apt-get install -y \
    php \
    php-xml
fi

if ! type wget 2>/dev/null; then
  apt-get install -y wget
fi

wget https://www.phing.info/get/phing-2.16.0.phar -O /usr/local/bin/phing
chmod +x /usr/local/bin/phing