#!/bin/sh

apt-get update
command -v php > /dev/null 2>&1 || { apt-get install -y php php-xml }
command -v wget > /dev/null 2>&1 || { apt-get install -y wget }
wget https://www.phing.info/get/phing-2.16.0.phar -O /usr/local/bin/phing
chmod +x /usr/local/bin/phing