#! /usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Install dependencies ' +
    'for running the TwinePM virtual machine.')

parser.parse_args()

subprocess.call(['apt-get', 'update'], stderr=subprocess.STDOUT)
subprocess.call(['apt-get', 'install', '-y', 'vagrant', 'virtualbox'],
                stderr=subprocess.STDOUT)

print('VM dependencies installed.')