#! /usr/bin/env python3

import argparse
import shutil
import subprocess
import urllib.request as request

parser = argparse.ArgumentParser(description='Install dependencies ' +
    'for the TwinePM host machine.')

parser.parse_args()

cmd = "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | " + \
    "sudo apt-key add -"

out = subprocess.check_output(cmd, shell=True)

proc = subprocess.Popen(['apt-key', 'fingerprint', '0EBFCD88'])
proc.communicate()

arch = '[arch=amd64]'
url = 'https://download.docker.com/linux/ubuntu'
dist = subprocess.check_output(['lsb_release', '-cs']).decode('utf-8')

branch = 'stable'
repo = 'deb {} {} {} {}'.format(arch, url, dist, branch)
cmd = ['add-apt-repository', repo]
proc = subprocess.Popen(cmd)
proc.communicate()

cmd = ['apt-get', 'update']
proc = subprocess.Popen(cmd)
proc.communicate()

cmd = ['apt-get', 'install', '-y', 'docker-ce']
proc = subprocess.Popen(cmd)
proc.communicate()

version = '1.16.1'
uname_s = subprocess.check_output(['uname', '-s']).decode('utf-8').strip('\n')
uname_m = subprocess.check_output(['uname', '-m']).decode('utf-8').strip('\n')
url = ('https://github.com/docker/compose/releases/download/{}/' +
    'docker-compose-{}-{}').format(version, uname_s, uname_m)
print(url)
file_name = '/usr/local/bin/docker-compose'
with request.urlopen(url) as response:
    with open(file_name, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)

proc = subprocess.Popen(['chmod', '+x', '/usr/local/bin/docker-compose'])
proc.communicate()

url = ('https://raw.githubusercontent.com/docker/compose/{}/contrib/' +
    'completion/bash/docker-compose').format(version)
file_name = '/etc/bash_completion.d/docker-compose'
with request.urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)

print('Installed host dependencies.')