#! /usr/bin/env python3

import argparse
import subprocess
import urllib.request as request

parser = argparse.ArgumentParser(description='Install dependencies ' +
    'for the TwinePM host machine.')

parser.parse_args()

cmd = "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | " + \
    "sudo apt-key add -"

print(subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True))

proc = subprocess.Popen(['apt-key', 'fingerprint', '0EBFCD88'],
                        stderr=subprocess.STDOUT)
proc.communicate()

arch = '[arch=amd64]'
url = 'https://download.docker.com/linux/ubuntu'
dist = '$(lsb_release -cs)';
cmd = ['add-apt-repository', 'deb', arch, url, dist, 'stable']
proc = subprocess.Popen(cmd, stderr=subprocess.STDOUT)
proc.communicate()

proc = subprocess.Popen(['apt-get', 'update'], stderr=subprocess.STDOUT)
proc.communicate()

cmd = ['apt-get', 'install', '-y', 'docker-ce']
proc = subprocess.Popen(cmd, stderr=subprocess.STDOUT)
proc.communicate()

version = '1.16.1'
uname_s = subprocess.check_output(['uname', '-s'], stderr=subprocess.STDOUT)
uname_m = subprocess.check_output(['uname', '-m'], stderr=subprocess.STDOUT)
url = ('https://github.com/docker/compose/releases/download/{}/' +
    'docker-compose-{}-{}').format(version, uname_s, uname_m)
file_name = '/usr/local/bin/docker-compose'
with request.urlopen(url) as response:
    with open(file_name, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)

url = ('https://raw.githubusercontent.com/docker/compose/{}/contrib/' +
    'completion/bash/docker-compose').format(version)
file_name = '/etc/bash_completion.d/docker-compose'
with request.urlopen(url) as response, open(file_name, 'wb') as out_file:
    shutil.copyfileobj(response, out_file)

print('Installed host dependencies.')