#! /usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Rebuild containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--removeall', '-r', action='store_true',
                    default=None, help='remove ')

parser.add_argument('--fromcache', '-f', '-c', action='store_true',
                    default=None,
                    help='do not replace the images; rather, build ' +
                        'from the cache if possible')

parser.add_argument('--start', '-s', '--up', '-u', action='store_true',
                    default=None, help='bring the containers online')

args = parser.parse_args()

cmd = ['removeContainers']
if args.removeall:
    cmd.append('--removeall')

proc = subprocess.Popen(cmd, stderr=subprocess.STDOUT)
proc.communicate()

cmd = ['buildContainers']
if args.fromcache:
    cmd.append('--fromcache')

proc = subprocess.Popen(cmd, strerr=subprocess.STDOUT)
proc.communicate()

if args.start:
    proc = subprocess.Popen(['startContainers'], stderr=subprocess.STDOUT)
    proc.communicate()

print('Container images rebuilt.')