#! /usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Rebuild containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--force', '-f', action='store_true', default=None,
                    help='don\'t ask for confirmation')

parser.add_argument('--dev', '-d', action='store_true',
                    default=None,
                    help='get the dev branch from the repository')

args = parser.parse_args()

cmds = ['destroyVm']
if args.force:
    cmds.append('--force')

subprocess.call(cmds, stderr=subprocess.STDOUT)

cmds = ['runVm']
if args.dev:
    cmds.append('--dev')

subprocess.call(cmds, stderr=subprocess.STDOUT)