#! /usr/bin/env python3

import argparse
import subprocess

parser = argparse.ArgumentParser(description='Rebuild containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--removeall', '-r', action='store_true',
                    default=None, help='remove ')

parser.add_argument('--fromcache', '-f', '-c', action='store_true',
                    default=None,
                    help='do not replace the images; rather, build ' +
                        'from the cache if possible')

parser.add_argument('--start', '-s', '--up', '-u', action='store_true',
                    default=None, help='bring the containers online')

args = parser.parse_args()

cmds = ['removeContainers']
if args.removeall:
    cmds.append('--removeall')

subprocess.call(cmds, stderr=subprocess.STDOUT)

cmds = ['buildContainers']
if args.fromcache:
    cmds.append('--fromcache')

subprocess.call(cmds, strerr=subprocess.STDOUT)

if args.start:
    subprocess.call(['startContainers'], stderr=subprocess.STDOUT)

print('Container images rebuilt.')