#! /bin/sh

docker-compose down &&

if [ "$1" == "fromcache" || "$1" == "--from-cache" || "$1" == "-c" ];
    docker-compose build
else
    docker-compose build --no-cache
fi &&

shift &&

if [ "$1" == "up" || "$1" == "--up" || "$1" == "-u" ];
    docker-compose up
fi