#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')

parser = argparse.ArgumentParser(description='Remove containerized ' +
                                 'versions of TwinePM services.')

parser.add_argument('--removeall', '-r', action='store_true',
                    default=None,
                    help='remove container images, volumes, and networks')

args = parser.parse_args()

cmd = ['docker-compose', '-f', compose_path]
if args.removeall:
    cmds.append(cmd, 'down')
else:
    cmds.append(cmd, 'rm')

proc = subprocess.Popen(cmd)
proc.communicate()

print('Containers removed.')