#! /usr/bin/env python3

import argparse
import subprocess
import os

dirname = os.path.dirname(os.path.realpath(__file__))
compose_path = os.path.join(dirname, '../docker-compose.yml')

parser = argparse.ArgumentParser(description='Remove containerized ' +
                                 'versions of TwinePM services.')

args = parser.parse_args()

cmd = ['docker-compose', '-f', compose_path, 'up']

proc = subprocess.Popen(cmd, strerr=subprocess.STDOUT)
proc.communicate()

print('Containers brought online.')