#! /usr/bin/env python3

import argparse
import subprocess
import os

path = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Start the ' +
                                 'containerized versions of TwinePM ' +
                                 'services.')

args = parser.parse_args()

cmd = ['docker-compose', '-f', '../docker-compose.yml', 'up']
proc = subprocess.Popen(cmd)
proc.communicate()

print('Container images started.')