#! /usr/bin/env python3

import argparse
import subprocess
import os

path = os.path.dirname(os.path.realpath(__file__))

parser = argparse.ArgumentParser(description='Start the ' +
                                 'containerized versions of TwinePM ' +
                                 'services.')

args = parser.parse_args()

subprocess.call(['docker-compose', '-f', '../docker-compose.yml', 'up'],
    stderr=subprocess.STDOUT)

print('Container images started.')